GA/GA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Login, log_out, HomePage


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^log-in$', Login.as_view(), name='login'),
    url(r'^log-out/$', log_out, name='log-out'),
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^reporte/', include('reporte.urls')),
    url(r'^rrhh/', include('rrhh.urls')),
]

GA/inventario/urls.py
from django.conf.urls import url
from .views import (
    UserCreate, MoveInCreate, MoveOutView, ProductClassCreate,
    ProductClassList, LandingPage, UserCreate, PrintCodes,
    PriceUpdateView, make_single_move_out,
    get_product_global_stock, get_product_class_details,
    get_products, get_product_stock, generate_file
)

app_name = 'inventario'
urlpatterns = [
    url(r'^create-user/$', UserCreate.as_view(), name='user-create'),
    url(r'^home/$', LandingPage.as_view(), name='home'),
    url(r'^product-create/$', ProductClassCreate.as_view(), name='create-product'),
    url(r'^print-product-codes/$', PrintCodes.as_view(), name='print-product-codes'),
    url(r'^product-search/$', ProductClassList.as_view(), name='product-class-search'),
    url(r'^product-out/$', MoveOutView.as_view(), name='move-out'),
    url(r'^product-in/$', MoveInCreate.as_view(), name='move-in'),
    url(r'^product-update-price/$', PriceUpdateView.as_view(), name='product-price-update'),
    url(r'^print-product-codes/$', PrintCodes.as_view(), name='print-codes'),
    url(r'^ajax/product_class_details/$', get_product_class_details, name='get_product_class'),
    url(r'^ajax/products/$', get_products, name='get-products'),
    url(r'^ajax/single-product-out/',make_single_move_out , name='single-move-out'),
    url(r'^ajax/get_product_stock', get_product_stock, name='get_product_stock'),
    url(r'^ajax/get_product_global_stock', get_product_global_stock, name='get_product_global_stock'),
    url(r'^ajax/generate_file', generate_file, name='generate-file'),
]

GA/inventario/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, CheckboxInput, PasswordInput

from GA import settings
from .models import ProductClass, MoveIn, MoveOut, User

class ProductClassForm(ModelForm):
    redirect = forms.CharField(max_length=50, required=False)
    is_disposable = forms.BooleanField(widget=CheckboxInput, required=False)
    cost_value = forms.FloatField(required=False)
    our_value = forms.FloatField(required=False)
    their_value = forms.FloatField(required=False)
    product_class = forms.IntegerField(required=False)

    class Meta:
        model = ProductClass
        fields = [
            'name',
            'product_type',
            'brand',
            'department',
            'size',
            'min_amount',
            'description',
            'is_disposable',
            'cost_value',
            'our_value',
            'their_value',
        ]


class MoveInForm(forms.Form):
    amount = forms.IntegerField()
    redirect = forms.CharField(max_length=50, required=False)
    destiny = forms.CharField(max_length=30)
    product_class = forms.IntegerField()


class MoveOutForm(forms.Form):
    redirect = forms.CharField(max_length=50, required=False)
    amount = forms.IntegerField()
    authorized_by = forms.IntegerField()
    received_by = forms.IntegerField()
    given_by = forms.IntegerField()
    reason = forms.CharField(max_length=15)
    reason_description = forms.CharField(max_length=300, required=False)
    from_location = forms.CharField(max_length=30)
    destiny = forms.CharField(max_length=30)
    product_class = forms.IntegerField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserCreateForm(forms.Form):
    redirect = forms.CharField(max_length=50, required=False)
    first_name = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    enterprise = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), initial=settings.ENTERPRISE)
    country = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), initial=settings.COUNTRY)
    city = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), initial=settings.CITY)
    designation = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}))
    admin = forms.BooleanField(widget=CheckboxInput(attrs={'class': 'form-control'}), required=False)


class CodesForm(forms.Form):
    product_class = forms.IntegerField()
    start = forms.IntegerField()
    end = forms.IntegerField()
    code_range = forms.IntegerField()


class PriceUpdateForm(forms.Form):
    increment = forms.FloatField()

GA/inventario/views.py
import json
import os

from django.http import JsonResponse
from django.core import serializers
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView, FormView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.encoding import smart_bytes

from GA import settings


from .forms import (
    ProductClassForm, MoveInForm, MoveOutForm, UserCreateForm,
    LoginForm, CodesForm, PriceUpdateForm
)
from .models import ProductClass, Product, MoveIn, MoveOut, User, Move_Out
from .code_generator import generate_full_code, create_codes_file


class LandingPage(LoginRequiredMixin, TemplateView):
    template_name = 'inventario/home.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super(LandingPage, self).get_context_data(**kwargs)
        products = []
        for product in ProductClass.objects.all().order_by('name', 'product_type', 'size', 'brand'):
            if product.department == 'Equipos y Enseres' or product.department == 'Maquinaria' or product.department == 'Computacion':
                continue
            else:
                if product.low_stock:
                    setattr(product, 'stock_almacen', Product.objects.filter(product_class=product.pk, available=True, location=settings.PRIMARY_LOCATION).count())
                    products.append(product)

        context['products'] = products
        return context



class UserCreate(LoginRequiredMixin, FormView):
    form_class = UserCreateForm
    template_name = 'inventario/user/user_form.html'
    success_url = reverse_lazy('inventario:home')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email = form.cleaned_data['email']
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        enterprise = form.cleaned_data['enterprise']
        country = form.cleaned_data['country']
        city = form.cleaned_data['city']
        designation = form.cleaned_data['designation']
        admin = form.cleaned_data['admin']
        try:
            user = User.objects.create_user(
                username=username,
                email=email,
                password=password,
                first_name=first_name,
                last_name=last_name,
            )
        except:
            form.add_error('username', 'User already exist')
            return super(UserCreate, self).form_invalid(form)
        user.enterprise = enterprise
        user.country = country
        user.city = city
        user.designation = designation
        user.admin = admin
        user.save()

        if "Save and Add another one" in form.cleaned_data['redirect']:
            self.success_url = reverse_lazy('inventario:move-in')

        return super(UserCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(UserCreate, self).get_context_data(**kwargs)
        context['is_superuser'] = json.dumps(self.request.user.is_superuser)
        return context


class ProductClassCreate(LoginRequiredMixin, CreateView):
    form_class = ProductClassForm
    template_name = 'inventario/product/product_class_form.html'
    success_url = reverse_lazy('inventario:home')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        if "Save and Add another one" in form.cleaned_data['redirect']:
            self.success_url = reverse_lazy('inventario:create-product')

        return super(ProductClassCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductClassCreate, self).get_context_data(**kwargs)
        context['is_superuser'] = json.dumps(self.request.user.is_superuser)
        context['is_staff'] = json.dumps(self.request.user.is_staff)
        return context


class ProductClassList(LoginRequiredMixin, FormView):
    form_class = ProductClassForm
    template_name = 'inventario/product/product_class_list.html'
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('inventario:home')

    def form_valid(self, form):
        pk = form.cleaned_data['product_class']
        product_class = ProductClass.objects.get(pk=pk)
        product_class.name = form.cleaned_data['name']
        product_class.brand = form.cleaned_data['brand']
        product_class.product_type = form.cleaned_data['product_type']
        product_class.size = form.cleaned_data['size']
        product_class.department = form.cleaned_data['department']
        product_class.description = form.cleaned_data['description']
        product_class.min_amount = form.cleaned_data['min_amount']
        product_class.is_disposable = form.cleaned_data['is_disposable']
        product_class.cost_value = form.cleaned_data['cost_value']
        product_class.our_value = form.cleaned_data['our_value']
        product_class.their_value = form.cleaned_data['their_value']
        product_class.save()

        return super(ProductClassList, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductClassList, self).get_context_data(**kwargs)
        context['products'] = serializers.serialize(
            'json',
            ProductClass.objects.all().order_by('name')
        )
        return context


class MoveInCreate(LoginRequiredMixin, FormView):
    form_class = MoveInForm
    template_name = 'inventario/move/move_in_form.html'
    success_url = reverse_lazy('inventario:home')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        destiny = form.cleaned_data['destiny']
        pk = form.cleaned_data['product_class']
        amount = form.cleaned_data['amount']
        user = self.request.user
        products = []

        product_class = ProductClass.objects.get(pk=pk)
        move_in = MoveIn.objects.create(
            destiny=destiny,
            product_class=product_class,
        )
        amount_of_products = Product.objects.filter(
            product_class=product_class,
        ).count()

        for i in range(amount):
            product_number = amount_of_products + i + 1
            full_code = generate_full_code(
                user,
                product_class,
                product_number
            )
            product = Product.objects.create(
                product_class=product_class,
                full_code=full_code,
                available=True,
                location=destiny,
                number=product_number,
            )
            product.save()
            products.append(product)

        move_in.products.add(*products)

        if "Save and Add another one" in form.cleaned_data['redirect']:
            self.success_url = reverse_lazy('inventario:move-in')

        return super(MoveInCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(MoveInCreate, self).get_context_data(**kwargs)
        context['is_superuser'] = json.dumps(self.request.user.is_superuser)
        return context


class MoveOutView(LoginRequiredMixin, FormView):
    form_class = MoveOutForm
    template_name = 'inventario/move/move_out_form.html'
    success_url = reverse_lazy('inventario:home')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super(MoveOutView, self).get_context_data(**kwargs)
        context['product_class'] = serializers.serialize(
            'json', ProductClass.objects.all())
        context['admin_users'] = serializers.serialize(
            'json', User.objects.filter(admin=True))
        context['retrieving_users'] = serializers.serialize(
            'json', User.objects.all())
        context['current_user'] = serializers.serialize(
            'json', [self.request.user])
        context['locations'] = json.dumps(settings.LOCATIONS)
        context['reasons'] = json.dumps(settings.MOVEMENT_REASONS)
        context['is_superuser'] = json.dumps(self.request.user.is_superuser)
        return context

    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        product_class_pk = form.cleaned_data['product_class']
        origin = settings.LOCATIONS[int(form.cleaned_data['from_location'])]
        destiny = settings.LOCATIONS[int(form.cleaned_data['destiny'])]
        reason = settings.MOVEMENT_REASONS[int(form.cleaned_data['reason'])]
        reason_description = form.cleaned_data['reason_description']
        authorized_by = form.cleaned_data['authorized_by']
        received_by = form.cleaned_data['received_by']
        given_by = self.request.user.pk

        product_class = ProductClass.objects.get(pk=product_class_pk)

        products = Product.objects.filter(
            product_class=product_class,
            location=origin,
        ).order_by('pk')[:amount]
        print(products)
        # If it's going to become unavailable
        if destiny == settings.LOCATIONS[4] or product_class.is_disposable:
            for product in products:
                product.location = destiny
                product.available = False
                product.save()
        else:
            for product in products:
                product.location = destiny
                product.save()

        move_out = Move_Out.objects.create(
            origin=origin,
            destiny=destiny,
            product_class=product_class,
            authorized_by=authorized_by,
            received_by=received_by,
            given_by=given_by,
            reason=reason,
            reason_description=reason_description,

GA/templates/inventario/move/move_in_form.html
{% extends 'inventario/layout.html' %}
{% load staticfiles %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {% if request.user.is_superuser %}
    <div class="text-center">
      <h1 class="display-2">Make Move In</h1>
      <p class="form-errors">{{ form.errors|striptags }}</p>
    </div>
    <div id="root"></div>
    <div class="text-center">
      <div class="btn-group">
        <button id="id_redirect" name="redirect" class="btn btn-primary btn-lg" value="" onClick="changeRedirect()">Submit and Add</button>
        <input type="submit" class="btn btn-primary btn-lg" value="Submit"/>
        <a href="{% url 'inventario:move-in' %}" class="btn btn-primary btn-lg">Clear Fields</a>
      </div>
    </div>
    <br/>
    <div class="row text-center">
      <div class="col">
        <a href="{% url 'inventario:home' %}" class="btn btn-danger btn-lg">Cancel</a>
      </div>
    </div>
  {% else %}
    <div class="text-center">
      <h1 class="display-2">Entrada de Producto</h1>
      <p class="form-errors">{{ form.errors|striptags }}</p>
    </div>
    <div id="root"></div>
    <div class="text-center">
      <div class="btn-group">
        <button id="id_redirect" name="redirect" class="btn btn-primary btn-lg" value="" onClick="changeRedirect()">Cargar y Añadir Otro</button>
        <input type="submit" class="btn btn-primary btn-lg" value="Cargar"/>
        <a href="{% url 'inventario:move-in' %}" class="btn btn-primary btn-lg">Limpiar Campos</a>
      </div>
    </div>
    <br/>
    <div class="row text-center">
      <div class="col">
        <a href="{% url 'inventario:home' %}" class="btn btn-danger btn-lg">Cancelar</a>
      </div>
    </div>
  {% endif %}
</form>
{% endblock %}

{% block extra_scripts %}
<script>
let en = JSON.parse('{{is_superuser}}');
function changeRedirect() {
  document.getElementById('id_redirect').value = "Save and Add another one";
  return;
}
</script>
<script type="text/babel" src="{% static 'react/product_details.js' %}"></script>
<script type="text/babel">
$(document).ready(function () {
  $.ajax({
    url: '/inventario/ajax/products/',
    data: {
      'products': true
    },
    dataType: 'json',
    success: function (data) {
      ReactDOM.render(
        <ProductDetails products={data}/>,
        document.getElementById('root')
      );
    }
  });

});
</script>
{% endblock %}

GA/templates/inventario/move/move_out_form.html
{% extends 'inventario/layout.html' %}
{% load staticfiles %}

{% block content %}
<form method="post" autocomplete="off">
  {% csrf_token %}
  {% if request.user.is_superuser %}
    <div class="text-center">
      <h3 class="display-3">Make A Move Out</h3>
    </div>
    {% if form.errors %}
    <div class="text-center">
      <p class="form-errors">{{form.errors|striptags}}.</p>
    </div>
    {% endif %}
    <div id="root"></div>
    <div class="text-center">
      <div class="btn-group">
        <a href="{% url 'inventario:move-out' %}" class="btn btn-warning btn-lg"><span style="color: white;">Clear Fields</span></a>
        <a href="{% url 'inventario:home' %}" class="btn btn-danger btn-lg">Cancel</a>
      </div>
    </div>
  {% else %}
    <div class="text-center">
      <h3 class="display-3">Movimiento de Productos o Desincorporacion</h3>
    </div>
    {% if form.errors %}
    <div class="text-center">
      <p class="form-errors">{{form.errors|striptags}}.</p>
    </div>
    {% endif %}
    <div id="root"></div>
    <div class="text-center">
      <div class="btn-group">
        <a href="{% url 'inventario:move-out' %}" class="btn btn-warning btn-lg"><span style="color: white;">Limpiar Campos</span></a>
        <a href="{% url 'inventario:home' %}" class="btn btn-danger btn-lg">Cancelar</a>
      </div>
    </div>
  {% endif %}
</form>
{% endblock %}

{% block extra_scripts %}
<script>
  let en = JSON.parse('{{is_superuser}}');
  function changeRedirect() {
    console.log('redirecting');
    document.getElementById('id_redirect').value = "Save and Add another one";
    return;
  }
  </script>
<script type="text/babel" src="{% static 'react/move_out_control.js' %}"></script>
<script type="text/babel">
  ReactDOM.render(
    <MoveOut
      move_out_url={'{% url "inventario:move-out" %}'}
      locations={JSON.parse('{{ locations | escapejs }}')}
      products={JSON.parse('{{ product_class | escapejs }}')}
      reasons={JSON.parse('{{ reasons | escapejs }}')}
      admin_users={JSON.parse('{{ admin_users | escapejs }}')}
      retrieving_users={JSON.parse('{{ retrieving_users | escapejs }}')}
      current_user={JSON.parse('{{ current_user | escapejs }}')}
    />,
    document.getElementById('root')
  );
</script>
{% endblock %}