GA/GA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Login, log_out, HomePage


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^log-in$', Login.as_view(), name='login'),
    url(r'^log-out/$', log_out, name='log-out'),
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^reporte/', include('reporte.urls')),
    url(r'^rrhh/', include('rrhh.urls')),
]

GA/rrhh/urls.py
from django.conf.urls import url
from . import views

app_name = 'rrhh'
urlpatterns = [
    url(r'^$', views.IndexRRHHView.as_view(), name='index'),
    url(r'^employee-list/$', views.ListEmployee.as_view(), name='employee-list'),
    url(r'^employee-create/$', views.CreateEmployee.as_view(), name='employee-create'),
    url(r'^employee-update/(?P<pk>\d+)/$', views.UpdateEmployee.as_view(), name='employee-update'),
    url(r'^employee-detail/(?P<pk>\d+)/$', views.DetailEmployee.as_view(), name='employee-detail'),
    url(r'^employee-delete/(?P<pk>\d+)/$', views.DeleteEmployee.as_view(), name='employee-delete'),

    url(r'^product-list/$', views.ListProduct.as_view(), name='product-list'),
    url(r'^product-create/$', views.CreateProduct.as_view(), name='product-create'),
    url(r'^product-update/(?P<pk>\d+)/$', views.UpdateProduct.as_view(), name='product-update'),
    url(r'^product-delete/(?P<pk>\d+)/$', views.DeleteEmployee.as_view(), name='product-delete'),

    url(r'^employee-control-list/$', 
        views.EmployeeControlListView.as_view(), name='employee-control-list'),
        
    url(r'^employee-control-create/(?P<pk>\d+)/$', 
        views.EmployeeControlView.as_view(), name='employee-control-create'),

    url(r'^employee-control-update/(?P<pk>\d+)/(?P<employee>\d+)/$', 
        views.EmployeeControlUpdateView.as_view(), name='employee-control-update'),

    url(r'^employee-control-delete/(?P<pk>\d+)/$', 
        views.EmployeeControlDeleteView.as_view(), name='employee-control-delete'),

    url(r'^employee-control-remove/(?P<pk>\d+)/$', 
        views.EmployeeControlRemoveView.as_view(), name='employee-control-remove'),
]

GA/rrhh/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from inventario.models import ProductClass


GENDER_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
    ('O', 'Otros'),
)

CIVIL_CHOICES = (
    ('S', 'Soltero'),
    ('C', 'Casado'),
    ('V', 'Viudo'),
)

PAY_RANGE_CHOICES = (
    ('S', 'Semanal'),
    ('Q', 'Quincenal'),
)

SHIFT_CHOICES = (
    ('D', 'Diurno'),
    ('N', 'Nocturno'),
    ('M', 'Mixto'),
)


class Employee(models.Model):
    employee_id = models.IntegerField(unique=True)  # Fingerprint ID
    name = models.CharField(max_length=128) # First and Second Name
    last_name = models.CharField(max_length=128) # First and Second Last Name
    cedula = models.IntegerField(unique=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, default='M')
    birthdate = models.DateField()
    address = models.CharField(max_length=256)
    civil_status = models.CharField(max_length=20, choices=CIVIL_CHOICES, default='S')
    home_phone = models.CharField(max_length=40, blank=True, null=True)
    mobile_phone = models.CharField(max_length=40, blank=True, null=True)
    fecha_de_ingreso = models.DateField(blank=True, null=True, default='1994-11-24')
    salario = models.FloatField(blank=True, null=True, default=1)
    salario_comida = models.FloatField(blank=True, null=True, default=1)
    salario_transporte = models.FloatField(blank=True, null=True, default=1)
    bono = models.FloatField(blank=True, null=True, default=1)
    fao = models.BooleanField(default=False)
    ivss = models.BooleanField(default=False)

    def __str__(self):
        return str(
            self.name + ' ' + self.last_name
        )

class Product(models.Model):
    name = models.CharField(max_length=250, default='')
    type = models.CharField(max_length=250, help_text="Talla, Color o Descripcion", default='')
    
class EmployeeControl(models.Model):
    CONTROL_TYPE = (
        ('I', 'Agregar'),
        ('O', 'Quitar'),
    )

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(ProductClass, on_delete=models.CASCADE, blank=True, null=True)
    type = models.CharField(max_length=20, choices=CONTROL_TYPE, default='I')
    date = models.DateField()
    amount = models.IntegerField(default=1)

    

GA/rrhh/forms.py
from django import forms
from django.forms import widgets
from django.forms import ModelForm
from django.forms import modelformset_factory

from .models import Employee, EmployeeControl, Product

class DateInput(forms.DateInput):
    input_type = 'date'

class EmployeeForm(ModelForm):
    
    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {
            'fecha_de_ingreso': DateInput(),
            'birthdate': DateInput()
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class' : 'form-control'})

        self.fields['employee_id'].label = 'ID del Empleado (Capta Huella)'
        self.fields['name'].label = 'Nombre'     
        self.fields['last_name'].label = 'Apellido'
        self.fields['gender'].label = 'Genero'
        self.fields['gender'].widget.attrs.update({'class' : 'selectpicker show-tick'})
        self.fields['birthdate'].label = 'Fecha de Nacimiento'
        self.fields['address'].label = 'Direccion'
        self.fields['civil_status'].label = 'Estado Civil'
        self.fields['civil_status'].widget.attrs.update({'class' : 'selectpicker show-tick'})
        self.fields['home_phone'].label = 'Telefono Hogar'
        self.fields['mobile_phone'].label = 'Telefono Personal'
        self.fields['mobile_phone'].required = False
        self.fields['salario_comida'].label = 'Bono de Alimentacion'
        self.fields['salario_transporte'].label = 'Transporte'
        self.fields['bono'].label = 'Bono'
        self.fields['fao'].label = 'FAO'
        
        self.fields['ivss'].label = 'IVSS'
        


class ProductForm(ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

class EmployeeControlForm(ModelForm):

    class Meta:
        model = EmployeeControl
        fields = ['product', 'date', 'amount']

class EmployeeControlUpdateForm(ModelForm):

    class Meta:
        model = EmployeeControl
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EmployeeControlUpdateForm, self).__init__(*args, **kwargs)
        self.fields['employee'].widget.attrs.update({'class' : 'selectpicker show-tick', 'data-live-search': True})
        self.fields['employee'].label = 'Empleado'
        self.fields['type'].widget.attrs.update({'class' : 'selectpicker show-tick'})
        self.fields['type'].label = 'Tipo'
        self.fields['product'].widget.attrs.update({'class' : 'selectpicker show-tick', 'data-live-search': True})
        self.fields['product'].label = 'Producto'
        self.fields['date'].widget.attrs.update({'class' : 'form-control'})
        self.fields['date'].label = 'Fecha'
        self.fields['amount'].widget.attrs.update({'class' : 'form-control'})
        self.fields['amount'].label = 'Cantidad'

EmployeeControlFormset = modelformset_factory(
    EmployeeControl,
    can_delete=False,
    extra=1,
    form=EmployeeControlForm,
    fields = ['product', 'date', 'amount']
)

GA/rrhh/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, FormView, TemplateView, DeleteView, DetailView
from django.views.generic.edit import FormMixin, UpdateView
from django.views.generic.list import ListView

from .forms import (EmployeeControlForm, EmployeeForm, ProductForm, EmployeeControlFormset, EmployeeControlUpdateForm)

from .models import Employee, EmployeeControl, Product
from inventario.models import ProductClass


class IndexRRHHView(LoginRequiredMixin, TemplateView):
    template_name = 'rrhh/index.html'
    login_url = reverse_lazy('inventario:login')


class ListEmployee(LoginRequiredMixin, TemplateView):
    template_name = 'rrhh/employee/employee-list.html'
    login_url = reverse_lazy('inventario:login')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employees'] = Employee.objects.all()
        return context

class CreateEmployee(LoginRequiredMixin, CreateView):
    template_name = 'rrhh/employee/employee-create.html'
    model = Employee
    form_class = EmployeeForm
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:index')

class UpdateEmployee(LoginRequiredMixin, UpdateView):
    template_name = 'rrhh/employee/employee-create.html'
    model = Employee
    form_class = EmployeeForm
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:employee-list')

class DeleteEmployee(LoginRequiredMixin, DeleteView):
    template_name = 'rrhh/employee/employee-delete.html'
    model = Employee
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:employee-list')

class DetailEmployee(LoginRequiredMixin, DetailView):
    template_name = 'rrhh/employee/employee-detail.html'
    context_object_name = 'employee'
    model = Employee
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')

    def get_context_data(self, **kwargs):
        context = super(DetailEmployee, self).get_context_data(**kwargs)
        employee = self.object
        context['total'] = employee.salario + employee.salario_comida + employee.salario_transporte + employee.bono
        return context


# Products Views
class CreateProduct(LoginRequiredMixin, CreateView):
    template_name = 'rrhh/product/product_form.html'
    model = Product
    form_class = ProductForm
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:index')

class UpdateProduct(LoginRequiredMixin, UpdateView):
    template_name = 'rrhh/product/product_form.html'
    model = Product
    form_class = ProductForm
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:product-list')

class ListProduct(LoginRequiredMixin, ListView):
    template_name = 'rrhh/product/product_list.html'
    model = Product
    context_object_name = 'products'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:index')


# Control Views
class EmployeeControlView(LoginRequiredMixin, CreateView):
    form_class = EmployeeControlForm
    template_name = 'rrhh/employee-control/control_form.html'
    model = EmployeeControl
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:employee-list')

    def get_queryset(self):
        employee_pk = self.kwargs.get(self.pk_url_kwarg)
        return Employee.objects.get(pk=employee_pk)

    def form_valid(self, form):
        if form.is_valid():
            control = form.save(commit=False)
            control.type = 'I'
            control.employee = self.get_queryset()
            control.save()

            return super().form_valid(form)

        return super().form_invalid(form)
            

    def get_context_data(self, **kwargs):
        context = super(EmployeeControlView, self).get_context_data(**kwargs)
        context['employee'] = self.get_queryset()
        context['products'] = ProductClass.objects.all()
        context['agregar'] = True
        return context


class EmployeeControlDeleteView(LoginRequiredMixin, CreateView):
    form_class = EmployeeControlForm
    template_name = 'rrhh/employee-control/control_form.html'
    model = EmployeeControl
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:employee-list')

    def get_queryset(self):
        employee_pk = self.kwargs.get(self.pk_url_kwarg)
        return Employee.objects.get(pk=employee_pk)

    def form_valid(self, form):
        if form.is_valid():
            control = form.save(commit=False)
            control.type = 'O'
            control.employee = self.get_queryset()
            control.save()

            return super().form_valid(form)

        return super().form_invalid(form)
            

    def get_context_data(self, **kwargs):
        context = super(EmployeeControlDeleteView, self).get_context_data(**kwargs)
        context['employee'] = self.get_queryset()
        context['products'] = ProductClass.objects.all()
        context['agregar'] = False
        return context


class EmployeeControlListView(LoginRequiredMixin, ListView):
    template_name = 'rrhh/employee-control/control-list.html'
    model = EmployeeControl
    context_object_name = 'controls'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:index')

class EmployeeControlUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'rrhh/product/product_form.html'
    model = EmployeeControl
    form_class = EmployeeControlUpdateForm
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')

    def get_success_url(self):
        return reverse('rrhh:employee-detail', kwargs={'pk': self.kwargs.get('employee')})


class EmployeeControlRemoveView(LoginRequiredMixin, DeleteView):
    template_name = 'rrhh/employee-control/control-remove.html'
    model = EmployeeControl
    pk_url_kwarg = 'pk'
    login_url = reverse_lazy('inventario:login')
    success_url = reverse_lazy('rrhh:employee-control-list')

GA/templates/rrhh/employee/employee-create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/loader.css' %}">
{% endblock %}

{% block content %}
<br/>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
<br />
<a class="btn btn-warning pull-right" href="{% url 'rrhh:index' %}">Menu RRHH</a>
<form class="mt-3 mb-3" method="POST">
        {% csrf_token %}
       <fieldset>
           <legend><strong> Datos del Empleado </strong></legend>
           <div class="row">
                <div class="form-group col-md-6">
                    <label> ID del Empleado (Capta Huella) </label>
                    {{ form.employee_id }}
                    {{ form.employee_id.errors }}
                </div>

                <div class="form-group col-md-6">
                    <label> C&eacute;dula </label>
                    {{ form.cedula }}
                    {{ form.cedula.errors }}
                </div>
           </div>
           <br/>
           <div class="row">
               <div class="form-group col-md-6">
                    <label> Nombre </label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>

                <div class="form-group col-md-6">
                    <label> Apellido </label>
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </div>
           </div>
       </fieldset>

       <hr />

       <fieldset>
            <legend><strong> Informac&oacute;n del Empleado </strong></legend>
            <div class="row">
                 <div class="form-group col-md-6">
                     <label> Fecha de Nacimiento </label>
                     {{ form.birthdate }}
                     {{ form.birthdate.errors }}
                 </div>
 
                 <div class="form-group col-md-6">
                     <label> Direcci&oacute;n </label>
                     {{ form.address }}
                     {{ form.address.errors }}
                 </div>
            </div>
            <br/>
            <div class="row">
                <div class="form-group col-md-6">
                     <label class="mr-1"> G&eacute;nero </label>
                     {{ form.gender }}
                     {{ form.gender.errors }}
                 </div>
 
                 <div class="form-group col-md-6">
                     <label class="mr-1"> Estado Civ&iacute;l </label>
                     {{ form.civil_status }}
                     {{ form.civil_status.errors }}
                 </div>
            </div>
        </fieldset>

        <hr />

       <fieldset>
            <legend><strong> N&uacute;meros de Contacto </strong></legend>
            <div class="row">
                 <div class="form-group col-md-6">
                     <label> Casa </label>
                     {{ form.home_phone }}
                     {{ form.home_phone.errors }}
                 </div>
 
                 <div class="form-group col-md-6">
                     <label> M&oacute;vil </label>
                     {{ form.mobile_phone }}
                     {{ form.mobile_phone.errors }}
                 </div>
            </div>
        </fieldset>

        <hr />

        <fieldset>
             <legend><strong> Datos Sociales </strong></legend>
             <div class="row">
                 <div class="form-group col-md-6">
                        <div class="checkbox checkbox-success">
                            {{ form.fao }}
                            <label for="id_fao"> FAO </label>
                        </div>
                 </div>
                  
  
                 <div class="form-group col-md-6">
                        <div class="checkbox checkbox-success">
                            {{ form.ivss }}
                            <label for="id_ivss"> IVSS </label>
                        </div>
                 </div>
             </div>
         </fieldset>

        {% if user.is_staff %}
        <hr />

       <fieldset>
            <legend><strong> Salarios </strong></legend>
            <div class="row">
                 <div class="form-group col-md-6">
                     <label> Base </label>
                     {{ form.salario }}
                     {{ form.salario.errors }}
                 </div>
 
                 <div class="form-group col-md-6">
                     <label> Bono de Alimentaci&oacute;n </label>
                     {{ form.salario_comida }}
                     {{ form.salario_comida.errors }}
                 </div>
            </div>
            <br />
            <div class="row">
                    <div class="form-group col-md-6">
                        <label> Transporte </label>
                        {{ form.salario_transporte  }}
                        {{ form.salario_transporte.errors }}
                    </div>
    
                    <div class="form-group col-md-6">
                        <label> Bono </label>
                        {{ form.bono }}
                        {{ form.bono.errors }}
                    </div>
               </div>
        </fieldset>
        {% endif %}
        <br />
        <div>
            <button type="submit" class="btn btn-success"> Submit </button>
            <a class="btn btn-danger" href="{% url 'rrhh:index' %}"> Cancel </a>
        </div>
</form>
{% endblock %}

{% block extra_scripts %}

{% endblock %}

GA/templates/rrhh/employee/employee-delete.html
{% extends 'base.html' %} 
{% load staticfiles %} 


{% block content %}
<br />
<div class="row">
    <div class="col-12">
        Confirm deletion of <i>"{{ object.name }} {{ object.last_name }} {{ object.cedula }}"</i>
    </div>
</div>
<div class="row mt-3">
    <div class="col-12">
        <form action="" method="POST">
            {% csrf_token %}
            <button class="btn btn-danger">Yes, delete "{{ object.name }} {{ object.last_name }} {{ object.cedula }}"</button>
        </form>
    </div>
</div>
{% endblock %}

GA/templates/rrhh/employee/employee-detail.html
{% extends 'base.html' %} 
{% load staticfiles %} 
{% load humanize %}
{% block content %}

<br />
<div>
    <h3 class="text-center"> <strong>{{ employee.name }} {{ employee.last_name }} | Cedula: {{ employee.cedula | intcomma }}</strong> </h3>
</div>
<br />
<div class="text-center">
    <h4><strong>Fecha de Ingreso:</strong> {{ employee.fecha_de_ingreso }}</h4>
    <h4><strong>FAO: </strong> {% if employee.fao == True %} S&iacute; {% else %} No {% endif %} -  <strong>IVSS:</strong> {% if employee.ivss == True %} S&iacute; {% else %} No {% endif %}</h4>
    {% if user.is_staff %}
        <br />
        <h4><strong>Salario Base: </strong>{{ employee.salario | intcomma }} - <strong>Bono de Alimentaci&oacute;n: </strong>{{ employee.salario_comida | intcomma }}</h4>
        <h4><strong>Transporte: </strong>{{ employee.salario_transporte | intcomma}} - <strong>Bono: </strong>{{ employee.bono | intcomma }}</h4>
        <h4> <strong>Total: </strong> {{ total | intcomma }}</h4>
    {% endif %}
</div>
<div>
    <a class="btn btn-success" href="{% url 'rrhh:employee-list' %}"> Lista de Empleados </a>
</div>

<br />
<table id="table" class="table table-responsive table-hover table-bordered text-center">
        <thead>
            <tr>
                <th> Producto </th>
                <th> Tipo </th>
                <th> Fecha </th>
                <th> Cantidad </th>
                <th> Acciones </th>
            </tr>
        </thead>
        
        <tbody>
            {% for control in employee.employeecontrol_set.all %}
            <tr>
                <td> {{ control.product }} </td>
                <td> 
                    {% if control.type == 'I' %} 
                        <a style="color: green;"><strong><i class="fa fa-arrow-up" aria-hidden="true"></i></strong></a> 
                    {% else %}
                        <a style="color: red;"><strong><i class="fa fa-arrow-down" aria-hidden="true"></i></strong></a>
                    {% endif %}
                </td>
                <td> {{ control.date }} </td>
                <td> {{ control.amount }} </td>
                <!-- Actions -->
                <td>
                    <!-- Update -->
                    <a href="{% url 'rrhh:employee-control-update' pk=control.pk employee=employee.id%}" class="mr-1"
                        data-toggle="tooltip" data-placement="left" title="Editar Control" style="color: black;">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                    
                    <!-- Remove -->
                    <a href="{% url 'rrhh:employee-control-remove' pk=control.pk %}" class="mr-1"
                        data-toggle="tooltip" data-placement="left" title="Remover Control" style="color: red;">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    
        <tfoot>
            <tr>
                <th> Producto </th>
                <th> Tipo </th>
                <th> Fecha </th>
                <th> Cantidad </th>
                <th> Acciones </th>
            </tr>
        </tfoot>
    </table>
{% endblock %}

{% block extra_scripts %}
<script>
    $(document).ready(function() {
        var table = $("#table").DataTable();

        $('[type=search]').on( 'keyup', function () {
            table.search( this.value ).draw();
        } );
    });
</script>
{% endblock extra_scripts %}

GA/templates/rrhh/employee/employee-list.html
{% extends 'base.html' %} 
{% load staticfiles %} 
{% load humanize %}
{% block content %}

<br />
<h2 class="text-center"> Lista de Empleados </h2>
<div>
    <a class="btn btn-danger" href="{% url 'rrhh:index' %}"> Menu Recursos Humanos </a>
</div>

<br />
<table id="table" class="table table-responsive table-hover table-bordered text-center">
    <thead>
        <tr>
            <th> Nombre </th>
            <th> Apellido </th>
            <th> Cedula </th>
            <th> Acciones </th>
            <th> Info del Empleado </th>
        </tr>
    </thead>
    
    <tbody>
        {% for employee in employees %}
        <tr>
            <td> {{ employee.name }} </td>
            <td> {{ employee.last_name }} </td>
            <td> {{ employee.cedula | intcomma }}</td>
            <!-- Actions -->
            <td>
                <!-- Update -->
                <a href="{% url 'rrhh:employee-update' pk=employee.pk %}" class="mr-1"
                    data-toggle="tooltip" data-placement="left" title="Edit {{ employee.name }}" style="color: black;">
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
                {% if user.is_staff %}
                <!-- Remove -->
                <a href="{% url 'rrhh:employee-delete' pk=employee.pk %}" class="mr-1"
                    data-toggle="tooltip" data-placement="left" title="Remove {{ employee.name }}" style="color: red;">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
                {% endif %}
                <span class="ml-2 mr-2"><strong>|</strong></span>
                <!-- Add Product -->
                <a href="{% url 'rrhh:employee-control-create' pk=employee.pk %}" class="mr-1"
                data-toggle="tooltip" data-placement="left" title="Asignar Producto" style="color: green;">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
                <!-- Remove Product -->
                <a href="{% url 'rrhh:employee-control-delete' pk=employee.pk %}" class="mr-1"
                    data-toggle="tooltip" data-placement="left" title="Remover Producto" style="color: red;"> 
                    <i class="fa fa-minus" aria-hidden="true"></i>
                </a>
            </td>
            <!-- Employee Detail -->
            <td>
                <a href="{% url 'rrhh:employee-detail' pk=employee.pk %}">
                    <i class="fa fa-address-card" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

    <tfoot>
        <tr>
            <th> Nombre </th>
            <th> Apellido </th>
            <th> Cedula </th>
            <th> Acciones </th>
            <th> Info del Empleado </th>
        </tr>
    </tfoot>
</table>
{% endblock %}

{% block extra_scripts %}
<script>
    $(document).ready(function() {
        var table = $("#table").DataTable();

        $('[type=search]').on( 'keyup', function () {
            table.search( this.value ).draw();
        } );
    });
</script>
{% endblock extra_scripts %}

GA/templates/rrhh/employee/employee-update.html
{% extends 'inventario/layout.html' %} 
{% load staticfiles %} 

{% block content %}
<form id="form" method="post">
     {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}